baseURL = "https://prometheus-workshop.roidelapluie.be/"
languageCode = "en-us"
title = "Prometheus Workshop"
theme = "minimal"
disqusShortname = ""
googleAnalytics = ""

[params]
    author = "Julien Pivotto"
    description = "Inuits 2020"
    githubUsername = "roidelapluie"
    accent = "#00a7c9"
    showBorder = true
    backgroundColor = "white"
    font = "Lato"
    highlight = true
    highlightStyle = "agate"
    highlightLanguages = ["yaml", "bash", "shell"]
copyright = "This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). Sponsored by [Inuits](https://inuits.eu) & [OSMC](https://osmc.de). Powered by [Hugo](https://gohugo.io) & [Minimal](https://github.com/calintat/minimal)."

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/info/"
    name = "Info"
    weight = 3

[[menu.main]]
    url = "/chapter/"
    name = "Workshop"
    weight = 4

[[menu.main]]
    url = "/2018/"
    name = "2018"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:roidelapluie@inuits.eu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/roidelapluie/prometheus-workshop"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://osmc.de/"
    name = "heart"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/intent/tweet?hashtags=OSMC,prometheus,workshop"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://docs.google.com/document/d/1kbhhCx_TpyamZo1K3ps_QxJrhwCV3Ti3D65jOACRZJs/edit?usp=sharing"
    name = "comment"
    weight = 4
